version: '3.2'
services:
  tensorflow:
    container_name: nlp-udemy-$USER
    build:
      context: .
    volumes:
      - ./src:/notebooks/src
      - ./data:/notebooks/large_files
    ports:
      - "8083:8888"
